= ocp_pick 

:numbered:

== Purpose
Do you often need to switch across many different OpenShift environments ?

In doing so, do you often struggle recollecting what user to log into as ?
Or what version of link:https://mirror.openshift.com/pub/openshift-v3/clients/?C=M;O=D[oc utility] to use ?

This utility provides assistance with login to one of many possible OpenShift Container Platform environments that you may have access to.

== Usage

. Download the latest release of this utility and place in a location on your $PATH:
+
-----
$ curl -L https://github.com/jbride/ocp_pick/releases/download/v.1/ocp_pick -o $HOME/bin/ocp_pick \
       && chmod 755 $HOME/bin/ocp_pick
-----

. This _ocp_pick_ utility reads a configuration file (in yaml format) of all of your OCP environments.
+
Download an example config file :
+
-----
$ curl https://raw.githubusercontent.com/jbride/ocp_pick/v.1/src/test/resources/ocp_env_details.yaml -o $HOME/ocp_env_details.yml
-----

. Edit this _$HOME/ocp_env_details.yml_ configuration file as necessary

. View the help:
+
-----
$ ocp_pick --help
-----



== Build and use from source

. Ensure link:https://www.oracle.com/technetwork/graalvm/downloads/index.html[GraalVM]  is installed and its _java_ and _javac_ utilities are in your $PATH
. Ensure Maven 3.5 (or more recent) is installed.
. Clone this git repo
. Change directory into this project

=== Native executable
. Build a java artifact and compile to a native executable:
+
-----
$ mvn clean package
-----

. Execute this utility as a native executable:
+
-----
$ ./target/ocp_pick --help
-----

. This maven project makes use of the _com.oracle.substratevm:native-image-maven-plugin_ for compilation to a native binary.
You can optionaly view the details of this plugin as follows:
+
-----
$ mvn help:describe -Dplugin=com.oracle.substratevm:native-image-maven-plugin -Ddetail
-----

=== Java byecode executable:

-----
$ mvn clean package -Dnative.skip=true
$ java -jar target/ocp_pick-1.0.jar
-----


-----
Warning: Reflection method java.lang.Class.forName invoked at org.yaml.snakeyaml.constructor.Constructor.getClassForName(Constructor.java:655)
Warning: Reflection method java.lang.Class.forName invoked at org.yaml.snakeyaml.constructor.Constructor.getClassForName(Constructor.java:653)
Warning: Reflection method java.lang.Class.getConstructor invoked at org.yaml.snakeyaml.constructor.Constructor$ConstructScalar.constructStandardJavaInstance(Constructor.java:433)
Warning: Reflection method java.lang.Class.getDeclaredConstructor invoked at org.yaml.snakeyaml.constructor.BaseConstructor.newInstance(BaseConstructor.java:302)
Warning: Reflection method java.lang.Class.getDeclaredConstructor invoked at org.yaml.snakeyaml.constructor.Constructor$ConstructScalar.construct(Constructor.java:385)
Warning: Reflection method java.lang.Class.getDeclaredConstructor invoked at org.yaml.snakeyaml.TypeDescription.newInstance(TypeDescription.java:387)
Warning: Reflection method java.lang.Class.getDeclaredConstructors invoked at org.yaml.snakeyaml.constructor.Constructor$ConstructSequence.construct(Constructor.java:529)
Warning: Reflection method java.lang.Class.getDeclaredConstructors invoked at org.yaml.snakeyaml.constructor.Constructor$ConstructScalar.construct(Constructor.java:356)
Warning: Reflection method java.lang.Class.getDeclaredFields invoked at org.yaml.snakeyaml.introspector.PropertyUtils.getPropertiesMap(PropertyUtils.java:97)
Warning: Reflection method java.lang.Class.getDeclaredFields invoked at org.yaml.snakeyaml.introspector.PropertyUtils.getPropertiesMap(PropertyUtils.java:71)
Warning: Abort stand-alone image build due to reflection use without configuration.
Warning: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
-----
