= GraalVM ocp_pick 

== Purpose
Do you often need to switch across many different OpenShift environments ?

In doing so, do you often struggle recollecting what user to log into as ?
Or what version of link:https://mirror.openshift.com/pub/openshift-v3/clients/?C=M;O=D[oc utility] to use ?

This utility provides assistance with login to one of many possible OpenShift Container Platform environments that you may have access to.

== Usage

. Download the latest release of this utility and place in a location on your $PATH:
+
-----
$ curl 
-----

. View the help:
+
-----
$ oc_pick --help
-----



== Build and use from source

. Ensure link:https://www.oracle.com/technetwork/graalvm/downloads/index.html[GraalVM]  is installed and its _java_ and _javac_ utilities are in your $PATH
. Ensure Maven 3.5 (or more recent) is installed.
. Clone this git repo
. Change directory into this project

=== Native executable
. Build a java artifact and compile to a native executable:
+
-----
$ mvn clean package
-----

. Execute this utility as a native executable:
+
-----
$ ./target/ocp_pick --help
-----

. This maven project makes use of the _com.oracle.substratevm:native-image-maven-plugin_ for compilation to a native binary.
You can optionaly view the details of this plugin as follows:
+
-----
$ mvn help:describe -Dplugin=com.oracle.substratevm:native-image-maven-plugin -Ddetail
-----

=== Java byecode executable:

-----
$ mvn clean package -Dnative.skip=true
$ java -jar target/ocp_pick-1.0.jar
-----

